
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox2;
	private global::Gtk.HBox hbox3;
	private global::Gtk.Button AddItem;
	private global::Gtk.Button UpdateButton;
	private global::Gtk.Button DeleteButton;
	private global::Gtk.Button ExitButton;
	private global::Gtk.ComboBox ItemChooser;
	private global::Gtk.HBox hbox4;
	private global::Gtk.CheckButton CompleteButton;
	private global::Gtk.Button button96;
	private global::Gtk.Entry ItemTitle;
	private global::Gtk.ScrolledWindow GtkScrolledWindow1;
	private global::Gtk.TextView ItemText;
	private global::Gtk.HBox hbox5;
	private global::Gtk.Button Back;
	private global::Gtk.Button AboutButton;
	private global::Gtk.Button Forward;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.AllowGrow = false;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Homogeneous = true;
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.AddItem = new global::Gtk.Button ();
		this.AddItem.CanFocus = true;
		this.AddItem.Name = "AddItem";
		this.AddItem.UseUnderline = true;
		// Container child AddItem.Gtk.Container+ContainerChild
		global::Gtk.Alignment w1 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w2 = new global::Gtk.HBox ();
		w2.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w3 = new global::Gtk.Image ();
		w3.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-add", global::Gtk.IconSize.LargeToolbar);
		w2.Add (w3);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w5 = new global::Gtk.Label ();
		w5.LabelProp = global::Mono.Unix.Catalog.GetString ("Add");
		w5.UseUnderline = true;
		w2.Add (w5);
		w1.Add (w2);
		this.AddItem.Add (w1);
		this.hbox3.Add (this.AddItem);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.AddItem]));
		w9.Position = 0;
		w9.Expand = false;
		w9.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.UpdateButton = new global::Gtk.Button ();
		this.UpdateButton.CanFocus = true;
		this.UpdateButton.Name = "UpdateButton";
		this.UpdateButton.UseUnderline = true;
		// Container child UpdateButton.Gtk.Container+ContainerChild
		global::Gtk.Alignment w10 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w11 = new global::Gtk.HBox ();
		w11.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w12 = new global::Gtk.Image ();
		w12.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-apply", global::Gtk.IconSize.LargeToolbar);
		w11.Add (w12);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w14 = new global::Gtk.Label ();
		w14.LabelProp = global::Mono.Unix.Catalog.GetString ("Save");
		w14.UseUnderline = true;
		w11.Add (w14);
		w10.Add (w11);
		this.UpdateButton.Add (w10);
		this.hbox3.Add (this.UpdateButton);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.UpdateButton]));
		w18.Position = 1;
		w18.Expand = false;
		w18.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.DeleteButton = new global::Gtk.Button ();
		this.DeleteButton.CanFocus = true;
		this.DeleteButton.Name = "DeleteButton";
		this.DeleteButton.UseUnderline = true;
		// Container child DeleteButton.Gtk.Container+ContainerChild
		global::Gtk.Alignment w19 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w20 = new global::Gtk.HBox ();
		w20.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w21 = new global::Gtk.Image ();
		w21.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-delete", global::Gtk.IconSize.LargeToolbar);
		w20.Add (w21);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w23 = new global::Gtk.Label ();
		w23.LabelProp = global::Mono.Unix.Catalog.GetString ("Delete");
		w23.UseUnderline = true;
		w20.Add (w23);
		w19.Add (w20);
		this.DeleteButton.Add (w19);
		this.hbox3.Add (this.DeleteButton);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.DeleteButton]));
		w27.Position = 2;
		w27.Expand = false;
		w27.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.ExitButton = new global::Gtk.Button ();
		this.ExitButton.CanFocus = true;
		this.ExitButton.Events = ((global::Gdk.EventMask)(256));
		this.ExitButton.Name = "ExitButton";
		this.ExitButton.UseUnderline = true;
		// Container child ExitButton.Gtk.Container+ContainerChild
		global::Gtk.Alignment w28 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w29 = new global::Gtk.HBox ();
		w29.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w30 = new global::Gtk.Image ();
		w30.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-close", global::Gtk.IconSize.LargeToolbar);
		w29.Add (w30);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w32 = new global::Gtk.Label ();
		w32.LabelProp = global::Mono.Unix.Catalog.GetString ("Exit");
		w32.UseUnderline = true;
		w29.Add (w32);
		w28.Add (w29);
		this.ExitButton.Add (w28);
		this.hbox3.Add (this.ExitButton);
		global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.ExitButton]));
		w36.Position = 3;
		w36.Expand = false;
		w36.Fill = false;
		this.vbox2.Add (this.hbox3);
		global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox3]));
		w37.Position = 0;
		w37.Expand = false;
		w37.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.ItemChooser = global::Gtk.ComboBox.NewText ();
		this.ItemChooser.Name = "ItemChooser";
		this.vbox2.Add (this.ItemChooser);
		global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.ItemChooser]));
		w38.Position = 1;
		w38.Expand = false;
		w38.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox ();
		this.hbox4.Name = "hbox4";
		this.hbox4.Homogeneous = true;
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.CompleteButton = new global::Gtk.CheckButton ();
		this.CompleteButton.CanFocus = true;
		this.CompleteButton.Name = "CompleteButton";
		this.CompleteButton.Label = global::Mono.Unix.Catalog.GetString ("Complete");
		this.CompleteButton.DrawIndicator = true;
		this.CompleteButton.UseUnderline = true;
		this.hbox4.Add (this.CompleteButton);
		global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.CompleteButton]));
		w39.Position = 0;
		// Container child hbox4.Gtk.Box+BoxChild
		this.button96 = new global::Gtk.Button ();
		this.button96.CanFocus = true;
		this.button96.Name = "button96";
		this.button96.UseUnderline = true;
		this.button96.Label = global::Mono.Unix.Catalog.GetString ("View History");
		this.hbox4.Add (this.button96);
		global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.button96]));
		w40.Position = 2;
		w40.Expand = false;
		w40.Fill = false;
		this.vbox2.Add (this.hbox4);
		global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox4]));
		w41.Position = 2;
		w41.Expand = false;
		w41.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.ItemTitle = new global::Gtk.Entry ();
		this.ItemTitle.CanFocus = true;
		this.ItemTitle.Name = "ItemTitle";
		this.ItemTitle.IsEditable = true;
		this.ItemTitle.InvisibleChar = '●';
		this.vbox2.Add (this.ItemTitle);
		global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.ItemTitle]));
		w42.Position = 3;
		w42.Expand = false;
		w42.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.ItemText = new global::Gtk.TextView ();
		this.ItemText.HeightRequest = 150;
		this.ItemText.CanFocus = true;
		this.ItemText.Name = "ItemText";
		this.ItemText.WrapMode = ((global::Gtk.WrapMode)(2));
		this.GtkScrolledWindow1.Add (this.ItemText);
		this.vbox2.Add (this.GtkScrolledWindow1);
		global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.GtkScrolledWindow1]));
		w44.Position = 4;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox ();
		this.hbox5.Name = "hbox5";
		this.hbox5.Homogeneous = true;
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.Back = new global::Gtk.Button ();
		this.Back.CanFocus = true;
		this.Back.Name = "Back";
		this.Back.UseUnderline = true;
		// Container child Back.Gtk.Container+ContainerChild
		global::Gtk.Alignment w45 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w46 = new global::Gtk.HBox ();
		w46.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w47 = new global::Gtk.Image ();
		w47.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-go-back", global::Gtk.IconSize.Menu);
		w46.Add (w47);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w49 = new global::Gtk.Label ();
		w49.LabelProp = global::Mono.Unix.Catalog.GetString ("Previous");
		w49.UseUnderline = true;
		w46.Add (w49);
		w45.Add (w46);
		this.Back.Add (w45);
		this.hbox5.Add (this.Back);
		global::Gtk.Box.BoxChild w53 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.Back]));
		w53.Position = 0;
		w53.Expand = false;
		w53.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.AboutButton = new global::Gtk.Button ();
		this.AboutButton.CanFocus = true;
		this.AboutButton.Name = "AboutButton";
		this.AboutButton.UseUnderline = true;
		// Container child AboutButton.Gtk.Container+ContainerChild
		global::Gtk.Alignment w54 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w55 = new global::Gtk.HBox ();
		w55.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w56 = new global::Gtk.Image ();
		w56.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-about", global::Gtk.IconSize.Menu);
		w55.Add (w56);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w58 = new global::Gtk.Label ();
		w58.LabelProp = global::Mono.Unix.Catalog.GetString ("Settings");
		w58.UseUnderline = true;
		w55.Add (w58);
		w54.Add (w55);
		this.AboutButton.Add (w54);
		this.hbox5.Add (this.AboutButton);
		global::Gtk.Box.BoxChild w62 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.AboutButton]));
		w62.Position = 1;
		w62.Expand = false;
		w62.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.Forward = new global::Gtk.Button ();
		this.Forward.CanFocus = true;
		this.Forward.Name = "Forward";
		this.Forward.UseUnderline = true;
		// Container child Forward.Gtk.Container+ContainerChild
		global::Gtk.Alignment w63 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w64 = new global::Gtk.HBox ();
		w64.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w65 = new global::Gtk.Image ();
		w65.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-go-forward", global::Gtk.IconSize.Menu);
		w64.Add (w65);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w67 = new global::Gtk.Label ();
		w67.LabelProp = global::Mono.Unix.Catalog.GetString ("Next");
		w67.UseUnderline = true;
		w64.Add (w67);
		w63.Add (w64);
		this.Forward.Add (w63);
		this.hbox5.Add (this.Forward);
		global::Gtk.Box.BoxChild w71 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.Forward]));
		w71.Position = 2;
		w71.Expand = false;
		w71.Fill = false;
		this.vbox2.Add (this.hbox5);
		global::Gtk.Box.BoxChild w72 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox5]));
		w72.Position = 5;
		w72.Expand = false;
		w72.Fill = false;
		this.Add (this.vbox2);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 384;
		this.DefaultHeight = 526;
		this.hbox4.Hide ();
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.AddItem.Clicked += new global::System.EventHandler (this.OnAddItemClicked);
		this.UpdateButton.Clicked += new global::System.EventHandler (this.OnUpdateButtonClicked);
		this.DeleteButton.Clicked += new global::System.EventHandler (this.OnDeleteButtonClicked);
		this.ExitButton.Clicked += new global::System.EventHandler (this.OnExitButtonClicked);
		this.ItemChooser.Changed += new global::System.EventHandler (this.OnItemChooserChanged);
		this.Back.Clicked += new global::System.EventHandler (this.OnBackClicked);
		this.AboutButton.Clicked += new global::System.EventHandler (this.OnAboutButtonClicked);
		this.Forward.Clicked += new global::System.EventHandler (this.OnForwardClicked);
	}
}
